// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Mojur.Unity.SolutionProcessing.Internal
{
    /// <summary>
    /// Interface for receiving solution synchronization calls.
    /// </summary>
    internal interface ISolutionSyncSubscriber
    {
        /// <summary>
        /// Called when the project files are about
        /// to be generated by Unity (.csproj and .sln files).
        /// </summary>
        /// <returns>True if the project files are generated; false otherwise.</returns>
        bool OnPreGeneratingCSProjectFiles();

        /// <summary>
        /// Called when the .sln solution file has completed generation.
        /// </summary>
        /// <param name="path">Full path of the .sln solution file.</param>
        /// <param name="content">Content of the .sln solution file in string form.</param>
        /// <returns>New content of the .sln solution file.</returns>
        string OnGeneratedSlnSolution(string path, string content);

        /// <summary>
        /// Called for each .csproj project file that has completed generation.
        /// </summary>
        /// <param name="path">Full path of the .csproj project file.</param>
        /// <param name="content">Content of the .csproj project file in string form.</param>
        /// <returns>New content of the .csproj project file.</returns>
        string OnGeneratedCSProject(string path, string content);

        /// <summary>
        /// Called when all project files have completed generation.
        /// </summary>
        void OnGeneratedCSProjectFiles();
    }
}
